config/routes.rb
MappedMoments::Application.routes.draw do

  root to: 'pages#home'

  match '/home', to: 'pages#home', via: 'get'
  match '/about', to: 'pages#about', via: 'get'

  resources :moments do
    collection do
      post 'mapsearch'
    end
  end

end

app/models/moment.rb
class Moment < ActiveRecord::Base

# exlicitly set table name
self.table_name = "moments"

# method validates data input when submitting a moment record
validates :title, presence: true
validates :latitude, presence: true
validates :longitude, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/moments_controller.rb
class MomentsController < ApplicationController

def new
end

def index
  @moments = Moment.all
end

def create
  @moment = Moment.new(mnt_params)

  if @moment.save
    redirect_to :root
  else
    # redirect to root for now (need to make show)
    # redirect_to :root
    # GEOCODE TEST WORKS!
    @search = Geocoder.coordinates(params[:moment][:search])
    render json: @search
  end

end

# AJAX call retirves coordinate data from place search for map
def mapsearch
  @search = Geocoder.coordinates(params[:place])
  #respond_to do |format|
  #  format.html { render :layout => false }
  #  format.js { render :layout => false }
  #end
  render json: @search
  #return @search
end

# private parameters defined for creating new cemetery records (ie what is required)
private

  def mnt_params
    allow = [:title,:latitude,:longitude]
    params.require(:moment).permit(allow)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

# dummy controller used for routing static layout pages
def home
end

def about
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moments_helper.rb
module MomentsHelper

# method uses ActionController and Gmaps4Rails model to build markers based on
# latitude and longitudinal values provided from an object
# @param: object/instance with latitude and longitude values (ie cemeteries)
# @return: marker hash containing lat and long values used by JS scripts to
# produce pin-points with info windows on a Google Maps instance
def add_markers(object)
  # use ActionController to create object instance to use render_to_string method
  info = ActionController::Base.new()
  @markers_hash = Gmaps4rails.build_markers(object) do |mnt, marker|
    if mnt.latitude != 0 && mnt.longitude != 0
      # set long and lat from cem object
      # NOTE: keep marker.lat and marker.lng named that, even if you change the column names
      #       only works like that and I dont know why
      marker.lat mnt.latitude
      marker.lng mnt.longitude
      # set info window to paritial view, pass cem object and path to partial
      marker.infowindow info.render_to_string(:partial => 'moments/infowindow', :locals => {:moment => mnt, path: moment_path(:id => mnt.id_moment)})
    end
  end
  return @markers_hash
end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
</div>

app/views/layouts/_header.html.erb
<div id="header" class="navbar navbar-static-top">
  <div class="navbar-inner">  
    <ul class="nav nav-pills nav-justified">
      <li><%= link_to 'Home', home_path %></li>
      <li><%= link_to 'About Us', about_path %></li>
      <li><%= link_to 'Add a Moment', new_moment_path %></li>
    </ul>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MappedMoments</title>
  <!-- include javascripts for gmaps4rails, Google Maps Support -->
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript">
  </script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'>
  </script>
  <!-- include javascript for Jquery -->
  <script src="http://code.jquery.com/jquery-2.0.3.min.js"></script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

<div id="wrapper">

    <!-- header of webpage -->
    <%= render 'layouts/header' %>

    <div id="main">

        <%= yield %>

    </div>

</div>

<!-- footer of webpage -->
<%= render 'layouts/footer' %>

</body>
</html>

app/views/moments/_infowindow.html.erb
<h4><%= moment.title %></h4>
<!-- NOTE: path is set in helpers since cant use normal _paths in partials -->
<%# link_to 'Load Moment Information', path %>

app/views/moments/new.html.erb
<h1>Create a Moment</h1>
<%= form_for :moment, url: moments_path do |mnt| %>
<p>
  <%= mnt.label "Moment title:" %>
  <%= mnt.text_field :title %>
</p>
<p>
  <%= mnt.label "Description:" %>
  <%= mnt.text_area :description %>
</p>
<p>
  <%= mnt.label "Latitude:" %>
  <%= mnt.text_field :latitude %>
</p>
<p>
  <%= mnt.label "Longitude:" %>
  <%= mnt.text_field :longitude %>
</p>
<h1>Search</h1>
<p>
  <%= mnt.text_field :search %>
</p>
<br/>
<p>
  <%= mnt.submit "Submit", class: "btn btn-large btn-primary" %>
  <%= mnt.submit "Reset Form", :type => "reset", class: "btn btn-danger" %>
</p>
<% end %>

app/views/pages/about.html.erb
<h4>About Us!</h4>

app/views/pages/home.html.erb
<!-- MAIN OVERVIEW MAP -->
<div id="map_container" class="map">
  <!-- implement simple google map api example -->
  <div id="map" class="fill"></div>
</div>


<!-- Generate Map with javascript -->
<!-- NOTE: set to Alberta for now -->
<script type="text/javascript">

  // INITIAL MAP 
  // NOTE: build JS function for this in future
  var mapOptions = {
  // disable scroll wheel due to map size
  scrollwheel: true,
  // Long and Lat for Alberta in general
  center: new google.maps.LatLng(54.800,-109.000),
  // zoom 6 for just Alberta
  zoom: 6
  };    
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: mapOptions, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw add_markers(Moment.all).to_json %>);
  handler.fitMapToBounds();
  });

  // add submit button functionality for coordinate search (geocoding using google API)
  // NOTE: Will change to incorporate Geocoder Gem functionality for geocoding
  var geocoder = new google.maps.Geocoder();
  function codeAddress() {
      var address = document.getElementById('searchText').value;
      geocoder.geocode( { 'address': address}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        var local_mapOptions = {
        scrollwheel: true,
        center: new google.maps.LatLng(results[0].geometry.location.lat(),results[0].geometry.location.lng()),
        zoom: 8
        };

        // new marker for map (uses json array)
        var searched_marker = [{'lat' : results[0].geometry.location.lat(), 'lng' : results[0].geometry.location.lng()}];

        // create json array of markers (including searched for location)
        var moment_markers = <%=raw add_markers(Moment.all).to_json %>;
        moment_markers = moment_markers.concat(searched_marker);

        // call global handler
        handler.buildMap({ provider: local_mapOptions, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(moment_markers);
        handler.fitMapToBounds();
        });
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
  });
}


</script>


<h1>Search</h1>
<p>
  <%= text_field :moment, :search, id: "searchText" %>
</p>
<br/>
<p>
  <%= button_tag "Search", type: "button", class: "btn btn-large btn-primary", id: "submitButton", onclick: "codeAddress()" %>
</p>

<script type="text/javascript">
/* $(function () { 
    map_search();
}); */

 function map_search() {
    /* create new map, reload markers, redefine center */
    $("#submitButton").click(function() {
        /* use AJAX to pass value to controller */
        $.ajax({
              type: 'POST',
              url: 'moments/mapsearch',
              data: { place: $("input[name='moment[search]']").val() },
              success: function(data) {
                           var mapOptions = {
	                       scrollwheel: false,
                               center: new google.maps.LatLng(data[0],data[1]),
	                       zoom: 6
	                   };
                           $("input[name='moment[search]']").val(data);
	                   var map = document.getElementById('map');
	                   var newmap = new google.maps.Map(map,mapOptions);
	                   map.map = newmap;
                       }
        });
	//var newcenter = new google.maps.LatLng(51.013117,-114.0741556);
    });
}
</script>